#!/usr/bin/perl

use strict;
use warnings;

#use diagnostics -verbose;

use File::Basename;
use File::Spec;
use File::Path;
use File::Copy;
use Cwd;

my $TESTSTATE_PWD = getcwd();
my $TESTSTATE_LASTRUN_STD;
my $TESTSTATE_LASTRUN_ERR;
my $TESTSTATE_LAST_OUTPUT;
my $TESTSTATE_TEST_NAME;



sub clear_test_env
{
	undef $TESTSTATE_PWD;
	undef $TESTSTATE_LASTRUN_STD;
	undef $TESTSTATE_LASTRUN_ERR;
	undef $TESTSTATE_LAST_OUTPUT;
	undef $TESTSTATE_TEST_NAME;

	system( 'rm -rv /tmp/gfstest/' );
}


sub testname
{
	my $name = shift;
	$TESTSTATE_TEST_NAME = $name;
}	

sub mkdirs($)
{
	my $dir = shift;

	# my $dirx = dirname $dir;

	# print "MKDIRS:[$dir]\n";
	eval { mkpath( $dir, 1 ) };
	$@ and die "Couldn't create dir path: $! $@";
	die "Did not find new path" if not -d $dir;

	return 1;
}

my %shaForSeed;

sub mkfile($$)
{
	my $path = shift;
	my $seed = shift;

	mkdirs(dirname($path) );

	open FILE, ">$path" or die "Cannot open $path: $!";
	print FILE "X-$seed" x 100;
	close FILE;

	$shaForSeed{$seed} = getSha( $path );

	print "$TESTSTATE_TEST_NAME - mkfile - $seed - $path\n";

}

sub getSha
{
	my $path = shift;
	my $sha = `shasum $path`;
	chomp $sha; 
	($sha =~ /^([^\s]+)\s/ ) or die;
	my $r = $1; 
	chomp $r;
	return $r;
}

sub cd($)
{
	my $newpath = shift;
	$TESTSTATE_PWD = $newpath;

	die unless -e $TESTSTATE_PWD;
	die unless -d $TESTSTATE_PWD;
}

sub run($)
{
	my @c = @_;

	my $i = 0;
	my $runPrefix = "gfstest.run.$i";

	$TESTSTATE_LASTRUN_STD = "$runPrefix.stdout";
	$TESTSTATE_LASTRUN_ERR = "$runPrefix.stderr";

	my $cmd = "( cd $TESTSTATE_PWD && @c ) > $TESTSTATE_LASTRUN_STD 2> $TESTSTATE_LASTRUN_ERR";
	print "RUN:[$cmd]\n";
	system($cmd );

	{
		local $/ = undef;
		local *FILE;
		open FILE, "<$TESTSTATE_LASTRUN_STD";
		$TESTSTATE_LAST_OUTPUT = <FILE>;
		close FILE
	}
}

sub extractReportedChecksum
{
	my $k = shift;

	 # print $TESTSTATE_LAST_OUTPUT;

	die "failed to find CS" unless( $TESTSTATE_LAST_OUTPUT =~ /^SHA1\/FULL\/([\w\/]+)\s+.*$k$/m);
	my $r = $1;
	chomp $r;

 	# print "GFS reported $k -> $r\n";

	return $r; 
}

sub verifyReportedChecksum
{
	my $path = shift;
	my $seed = shift;

	my $r = extractReportedChecksum( $path );
	my $c = $shaForSeed{$seed};

	die "Verify Reported Checksum Failed - $path - $r ne $c" if( $r ne $c );

	print "$TESTSTATE_TEST_NAME - OK - gfs_checksum - $seed - $path\n";

}



sub verifyFile
{
	my $path = shift;
	my $seed = shift;

	my $found = getSha( $path );

	die "Verify Checksum Failed - $path - $found ne $shaForSeed{$seed}" if( $found ne $shaForSeed{$seed});

	print "$TESTSTATE_TEST_NAME - OK - verifyFile - $seed - $path\n";

}

use File::Copy;

sub move
{
	my $a = shift;
	my $b = shift;

	File::Copy->move( $a, $b );

	print "$TESTSTATE_TEST_NAME - mv - $a -> $b\n";
}

sub rm
{
	my $a = shift;

	unlink( $a );

	print "$TESTSTATE_TEST_NAME - rm - $a\n";
}

sub test_simplePathnames
{
	clear_test_env;
	testname 'test_simplePathnames';
	mkfile '/tmp/gfstest/file1', 15;
	mkfile '/tmp/gfstest/file2', 20;
	cd '/tmp/gfstest';
	run "gfs checksum file1 file2";

	verifyFile( '/tmp/gfstest/file1', 15 );
	verifyFile( '/tmp/gfstest/file2', 20 );

	verifyReportedChecksum( 'file1', 15 );

	rm '/tmp/gfstest/file1';

	verifyReportedChecksum( 'file1', 15 );

	run "gfs checksum -G 0 file1 file2";

	

}

test_simplePathnames();
